'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Encomendas

    '''<summary>
    '''progressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents progressBar As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''uplMainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplMainPanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.C1.Web.Wijmo.Controls.C1ComboBox.C1ComboBox

    '''<summary>
    '''ddlCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCliente As Global.C1.Web.Wijmo.Controls.C1ComboBox.C1ComboBox

    '''<summary>
    '''ddlDataPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDataPeriod As Global.C1.Web.Wijmo.Controls.C1ComboBox.C1ComboBox

    '''<summary>
    '''C1Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1Menu1 As Global.C1.Web.Wijmo.Controls.C1Menu.C1Menu

    '''<summary>
    '''C1MenuItem1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1MenuItem1 As Global.C1.Web.Wijmo.Controls.C1Menu.C1MenuItem

    '''<summary>
    '''C1MenuItem3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1MenuItem3 As Global.C1.Web.Wijmo.Controls.C1Menu.C1MenuItem

    '''<summary>
    '''C1MenuItem4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1MenuItem4 As Global.C1.Web.Wijmo.Controls.C1Menu.C1MenuItem

    '''<summary>
    '''C1Encomendas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1Encomendas As Global.C1.Web.Wijmo.Controls.C1GridView.C1GridView
End Class
