'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Vendas

    '''<summary>
    '''C1ComboBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1ComboBox3 As Global.C1.Web.Wijmo.Controls.C1ComboBox.C1ComboBox

    '''<summary>
    '''C1ComboBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1ComboBox4 As Global.C1.Web.Wijmo.Controls.C1ComboBox.C1ComboBox

    '''<summary>
    '''C1ComboBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1ComboBox5 As Global.C1.Web.Wijmo.Controls.C1ComboBox.C1ComboBox

    '''<summary>
    '''C1Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1Menu1 As Global.C1.Web.Wijmo.Controls.C1Menu.C1Menu

    '''<summary>
    '''C1MenuItem5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1MenuItem5 As Global.C1.Web.Wijmo.Controls.C1Menu.C1MenuItem

    '''<summary>
    '''C1MenuItem6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1MenuItem6 As Global.C1.Web.Wijmo.Controls.C1Menu.C1MenuItem

    '''<summary>
    '''C1MenuItem7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1MenuItem7 As Global.C1.Web.Wijmo.Controls.C1Menu.C1MenuItem

    '''<summary>
    '''C1GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C1GridView1 As Global.C1.Web.Wijmo.Controls.C1GridView.C1GridView
End Class
